// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnvConfig } from '@/lib/env-validation';

// Safe storage implementation that handles SSR/hydration
const safeStorage = {
  getItem: (key: string) => {
    if (typeof window !== 'undefined' && window.localStorage) {
      try {
        return window.localStorage.getItem(key);
      } catch (error) {
        console.warn('Failed to read from localStorage:', error);
        return null;
      }
    }
    return null;
  },
  setItem: (key: string, value: string) => {
    if (typeof window !== 'undefined' && window.localStorage) {
      try {
        window.localStorage.setItem(key, value);
      } catch (error) {
        console.warn('Failed to write to localStorage:', error);
      }
    }
  },
  removeItem: (key: string) => {
    if (typeof window !== 'undefined' && window.localStorage) {
      try {
        window.localStorage.removeItem(key);
      } catch (error) {
        console.warn('Failed to remove from localStorage:', error);
      }
    }
  }
};

// Lazy supabase client initialization
// Only validates environment when client is actually used
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabaseClient = () => {
  if (supabaseInstance) {
    return supabaseInstance;
  }
  
  try {
    const config = getEnvConfig();
    supabaseInstance = createClient<Database>(config.SUPABASE_URL, config.SUPABASE_ANON_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: 'pkce',
      },
      global: {
        headers: {
          'X-Client-Info': 'replify-ai/1.0'
        }
      },
      db: {
        schema: 'public'
      }
    });
    return supabaseInstance;
  } catch (error) {
    console.error('Failed to initialize Supabase client:', error);
    throw error;
  }
};

// For backward compatibility - this will trigger validation immediately
// Use getSupabaseClient() for lazy initialization
// export const supabase = getSupabaseClient();